=== OpenStack on FreeBSD

Links: +
link:https://www.openstack.org/[OpenStack] URL: link:https://www.openstack.org/[] +
link:https://github.com/starbops/osf[OpenStack on FreeBSD] URL: link:https://github.com/starbops/osf[] +

Contact: Chih-Hsin Chang <starbops@hey.com> +
Contact: Li-Wen Hsu <lwhsu@FreeBSD.org>

OpenStack is an open-source cloud operating system for resources such as virtual machines and bare metal.
However, OpenStack only unofficially supports FreeBSD as a guest system.
This means, users can spawn FreeBSD instances on the open cloud platform, but it is not currently possible to run https://docs.openstack.org/arch-design/design-control-plane.html[control plane] on FreeBSD hosts.
The goal of this project is to port key OpenStack components so that FreeBSD can function as an OpenStack host.

Academic and industrial research groups have been evaluating CHERI-enabled Morello boards since mid-2022.
A resource orchestration platform such as OpenStack can improve the speed and cost of provisioning, managing, and recycling these boards.

Starting in January 2022, Chih-Hsin Chang has been working to port several OpenStack components to run on FreeBSD, including:

* https://docs.openstack.org/keystone/latest/[keystone] (identity service)
* https://docs.openstack.org/glance/[glance] (image service)
* https://docs.openstack.org/placement/[placement] (resource tracking and inventory service)
* https://docs.openstack.org/neutron/[neutron] (networking service)
* https://docs.openstack.org/nova/[nova] (compute service).

Some of the items are still under heavy development.
For instance, due to the design of neutron, the DHCP servers are placed inside Linux network namespaces.
It is necessary to find an alternative, e.g. man:vnet[9], on FreeBSD and adapt it.
Most of the time the porting strategy is to make as small of an impact as possible by working around obstacles.
Something like https://docs.openstack.org/oslo.privsep/[oslo.privsep] deserves true porting. `oslo.privsep` is rooted in Linux capabilities to do the privilege separation work.
Right now we just bypass any Linux capabilities-related operation inside `oslo.privsep`.
So currently, there is plenty of hackish stuff in the source code and configurations.
All of these, along with the building and installation steps, will be collected in the https://github.com/starbops/osf[project repository].

In quarter four, Chih-Hsin plans to focus on porting neutron and nova in order to complete the VM lifecycle operations.
Highlights include:

* DHCP integration
* FreeBSD bridge driver/agent
* man:bhyve[8] + libvirt integration.

Sponsor: The FreeBSD Foundation
